SideProjects.BookmarkUrlLinks/Controllers/BookmarkUrlController.cs
using SideProjects.BookmarkUrlLinks.Models;
using SideProjects.BookmarkUrlLinks.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SideProjects.BookmarkUrlLinks.Controllers
{
    public class BookmarkUrlController : Controller
    {

        [HttpGet]
        [Route("add-bookmarks")]
        public ActionResult AddBookMark()
        {
            return View("~/Views/BookmarkUrl/AddBookmarkUrl.cshtml");
        }

        [HttpPost]
        [Route("add-bookmarks")]
        public ActionResult AddBookMark(UrlLink link)
        {
            if (ModelState.IsValid)
            {
                using (var db = new UserDb())
                {
                    var newLink = new UrlLink()
                    {
                        LinkID = link.LinkID,
                        Links = link.Links
                    };
                    db.UrlLink.Add(newLink);
                    db.SaveChanges();
                    return Redirect("get-bookmarks");
                }
            }
            else
            {
                return HttpNotFound("Error: Link is empty");
            }
            

        }

        [HttpGet]
        [Route("get-bookmarks")]
        public ActionResult GetLinks()
        {
            using (var db = new UserDb())
            {
                var getLink = from link in db.UrlLink
                              orderby link.LinkID ascending
                              select link;

                var displayLinks = getLink.ToList();

                return View("~/Views/BookmarkUrl/BookmarkUrlLayout.cshtml", displayLinks);

            }
        }


        [Route("delete-bookmarks")]
        public ActionResult DeleteLinksID(int id)
        {
            using (var db = new UserDb())
            {
                UrlLink urlLink = db.UrlLink.Find(id);

                return View("~/Views/BookmarkUrl/DeleteLinks.cshtml", urlLink);
            }
        }

        [HttpPost, ActionName("DeleteLinksID"), Route("delete-bookmarks")]
        public ActionResult DeleteLinks(int id)
        {
           
            using (var db = new UserDb())
            {
                var url = db.UrlLink.Find(id);
                db.UrlLink.Remove(url);
                db.SaveChanges();
            }

            return Redirect("get-bookmarks");
        }


        [HttpGet]
        [Route("html")]
        public ActionResult getHtml()
        {
            return View("~/Views/BookmarkUrl/HTML.cshtml");
        }
    }
}

SideProjects.BookmarkUrlLinks/Controllers/UserAccountController.cs
using SideProjects.BookmarkUrlLinks.Models;
using SideProjects.BookmarkUrlLinks.Context;
using System.Linq;
using System.Web.Mvc;
using System.Net;
using System.Collections.Generic;
using System.Web.Routing;

namespace SideProjects.BookmarkUrlLinks.Controllers
{
    public class UserAccountController : Controller
    {
        [HttpGet]
        [Route("home")]
        public ActionResult Homepage()
        {
            return View("~/Views/UserAccount/Homepage.cshtml");
        }

        [HttpGet]
        [Route("register")]
        public ActionResult CreateUserAccount()
        {
            return View("~/Views/UserAccount/RegisterAccount.cshtml");
        }

        [HttpPost]
        [Route("register")]
        public ActionResult CreateUserAccount(User user)
        {
            //if (user.UserName == null)
            //{
            //    return HttpNotFound("Error: Username is empty");
            //}
            //else if (user.Password == null)
            //{
            //    return HttpNotFound("Error: Password is empty");
            //}

            //check the model binding validation.
            if (ModelState.IsValid)
            {
                using (var db = new UserDb())
                {
                    var newUser = new User()
                    {
                        ID = user.ID,
                        UserName = user.UserName,
                        Password = user.Password
                    };

                    db.Users.Add(newUser);
                    db.SaveChanges();
                }
                return Redirect("get-user");
            }
            else
            {
                //404 Page will be display
                //return HttpNotFound("Error: Register fields are empty");

                List<string> errorMessage = ModelState.Values.SelectMany(v => v.Errors.Select(b => b.ErrorMessage)).ToList();
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, errorMessage.FirstOrDefault());
            }
        }

        [HttpGet]
        [Route("login")]
        public ActionResult Login()
        {
            return View("~/Views/UserAccount/Login.cshtml");
        }

        [HttpPost, ActionName("Login"), Route("login")]
        public ActionResult Login(User user)
        {
            if (ModelState.IsValid)
            {
                using (var db = new UserDb())
                {
                    var existingUser = db.Users.Where(a => a.UserName.Equals(user.UserName) && a.Password.Equals(user.Password)).FirstOrDefault();
                    if (existingUser != null)
                    {
                        return Redirect("add-bookmarks");
                    }
                    else
                    {
                        List<string> errorMessage = ModelState.Values.SelectMany(v => v.Errors.Select(b => b.ErrorMessage)).ToList();
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest, errorMessage.FirstOrDefault());
                    }
                }
            }
            return View(user);

        }

        [HttpGet]
        [Route("get-user")]
        public ActionResult GetRegisteredUser()
        {
            using (var db = new UserDb())
            {
                var getUser = from u in db.Users
                              orderby u.ID ascending
                              select u;

                var selectedUser = getUser.ToList<User>();

                return View("~/Views/UserAccount/UserRegistered.cshtml", selectedUser);
            }
        }

        [Route("api/delete/{name}")]
        public JsonResult DeleteUser(string name)
        {
            using (var db = new UserDb())
            {
                User getUserID = db.Users.Where(x => x.UserName == name).FirstOrDefault();

                db.Users.Remove(getUserID);
                db.SaveChanges();
            }
            return Json("Success");
        }
    }
}

SideProjects.BookmarkUrlLinks/Views/Shared/MasterLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="~/Assets/CSS/index.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
</head>
<body>
    <header>
        <div class="container">
            <a href="html">
                <h1>Bookmark Links</h1>
            </a>
            <nav>
                <ul>
                    <a href="login"><li>Login</li></a>
                    <a href="register"><li>Register</li></a>
                    <a href="add-bookmarks"><li>Bookmark link</li></a>
                </ul>
            </nav>
        </div>
    </header>
    <!-- <div class="jumbotron text-center">
        <div>
            <a href="add-bookmarks">
                <h1>Bookmark Links</h1>
            </a>
            <nav>
                <ul>
                    <a href="register"><li>Add user</li></a>
                    <li>Add bookmark link</li>
                    <li>Html testing page</li>
                    <li>@Html.ActionLink("Register", "CreateUserAccount", "UserAccount")</li>
                    <li>@Html.ActionLink("Bookmark Url Links", "AddBookMark", "BookmarkUrl")</li>
                </ul>
            </nav>
        </div>
    </div> -->
    <div>
        @RenderBody()
    </div>

    <footer>
        <p>Copyright &copy; 2019 Bookmark Links</p>
    </footer>


    <script src="~/Assets/JS/index.js" type="text/javascript"></script>


</body>
</html>

SideProjects.BookmarkUrlLinks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>